// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"telegleb/internal/adapter/repository/session"
	"telegleb/internal/adapter/telegram"
	"telegleb/internal/config"
	deliveryhttp "telegleb/internal/delivery/http"
	"telegleb/internal/core/usecase/auth"
	"telegleb/internal/core/usecase/messenger"
	"telegleb/internal/lib/jwt"
)

func provideTelegramAppID(cfg *config.Config) int {
	return cfg.Telegram.AppID
}

func provideTelegramAppHash(cfg *config.Config) string {
	return cfg.Telegram.AppHash
}

func provideTelegramProxyAddr(cfg *config.Config) string {
	return cfg.Telegram.ProxyAddr
}

func provideTelegramProxySecret(cfg *config.Config) string {
	return cfg.Telegram.ProxySecret
}

func provideJWTManager(cfg *config.Config) *jwt.TokenManager {
	return jwt.NewTokenManager(cfg.JWT.Secret, cfg.JWT.TTL)
}

func InitApp() (*App, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	logger := ProvideLogger(configConfig)
	client, err := ProvideRedis(configConfig, logger)
	if err != nil {
		return nil, err
	}
	int2 := provideTelegramAppID(configConfig)
	string2 := provideTelegramAppHash(configConfig)
	string3 := provideTelegramProxyAddr(configConfig)
	string4 := provideTelegramProxySecret(configConfig)
	sessionRepository := session.NewRedisSessionRepository(client)
	telegramAdapter := telegram.NewTelegramAdapter(int2, string2, string3, string4, sessionRepository, logger)
	tokenManager := provideJWTManager(configConfig)
	requestLoginUseCase := auth.NewRequestLoginUseCase(telegramAdapter, sessionRepository, tokenManager)
	verifyCodeUseCase := auth.NewVerifyCodeUseCase(telegramAdapter, sessionRepository)
	verifyPasswordUseCase := auth.NewVerifyPasswordUseCase(telegramAdapter, sessionRepository)
	logoutUseCase := auth.NewLogoutUseCase(telegramAdapter, sessionRepository)
	chatRepository := telegram.NewTelegramChatRepository(telegramAdapter)
	loadDashboardUseCase := messenger.NewLoadDashboardUseCase(chatRepository)
	messageRepository := telegram.NewTelegramMessageRepository(telegramAdapter)
	openChatUseCase := messenger.NewOpenChatUseCase(messageRepository)
	sendMessageUseCase := messenger.NewSendMessageUseCase(messageRepository)
	mediaRepository := telegram.NewTelegramMediaRepository(telegramAdapter)
	streamMediaChunkUseCase := messenger.NewStreamMediaChunkUseCase(mediaRepository)
	server := deliveryhttp.NewServer(configConfig, logger, requestLoginUseCase, verifyCodeUseCase, verifyPasswordUseCase, logoutUseCase, loadDashboardUseCase, openChatUseCase, sendMessageUseCase, streamMediaChunkUseCase)
	app := NewApp(configConfig, logger, client, server)
	return app, nil
}
