// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"telegleb/internal/adapter/repository/session"
	"telegleb/internal/adapter/telegram"
	"telegleb/internal/config"
	"telegleb/internal/core/usecase/auth"
	"telegleb/internal/core/usecase/messenger"
	"telegleb/internal/delivery/http"
	"telegleb/internal/lib/jwt"
)

// Injectors from wire.go:

func InitApp() (*App, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	logger := ProvideLogger(configConfig)
	client, err := ProvideRedis(configConfig, logger)
	if err != nil {
		return nil, err
	}
	tokenManager := provideJWTManager(configConfig)
	telegramConfig := provideTelegramConfig(configConfig)
	sessionRepository := session.NewRedisSessionRepository(client)
	telegramAdapter := telegram.NewTelegramAdapter(telegramConfig, sessionRepository, logger)
	requestCodeUseCase := auth.NewRequestCodeUseCase(telegramAdapter, sessionRepository, tokenManager)
	verifyCodeUseCase := auth.NewVerifyCodeUseCase(telegramAdapter, sessionRepository)
	verifyPasswordUseCase := auth.NewVerifyPasswordUseCase(telegramAdapter, sessionRepository)
	sessionUseCase := auth.NewSessionUseCase(telegramAdapter, sessionRepository)
	logoutUseCase := auth.NewLogoutUseCase(telegramAdapter, sessionRepository)
	chatRepository := telegram.NewTelegramChatRepository(telegramAdapter)
	loadDashboardUseCase := messenger.NewLoadDashboardUseCase(chatRepository)
	listTopicsUseCase := messenger.NewListTopicsUseCase(chatRepository)
	messageRepository := telegram.NewTelegramMessageRepository(telegramAdapter)
	openChatUseCase := messenger.NewOpenChatUseCase(messageRepository)
	sendMessageUseCase := messenger.NewSendMessageUseCase(messageRepository)
	mediaRepository := telegram.NewTelegramMediaRepository(telegramAdapter)
	streamMediaUseCase := messenger.NewStreamMediaUseCase(mediaRepository)
	server := http.NewServer(configConfig, logger, client, tokenManager, requestCodeUseCase, verifyCodeUseCase, verifyPasswordUseCase, sessionUseCase, logoutUseCase, loadDashboardUseCase, listTopicsUseCase, openChatUseCase, sendMessageUseCase, streamMediaUseCase)
	app := NewApp(configConfig, logger, client, server)
	return app, nil
}

// wire.go:

func provideTelegramConfig(cfg *config.Config) telegram.Config {
	return telegram.Config{
		AppID:       cfg.Telegram.AppID,
		AppHash:     cfg.Telegram.AppHash,
		ProxyAddr:   cfg.Telegram.ProxyAddr,
		ProxySecret: cfg.Telegram.ProxySecret,
	}
}

func provideJWTManager(cfg *config.Config) *jwt.TokenManager {
	return jwt.NewTokenManager(cfg.JWT.Secret, cfg.JWT.TTL)
}
